@file:Suppress("PackageDirectoryMismatch")
package algalon.auth.op
import algalon.settings.MAX_USERNAME_LEN
import algalon.utils.b

val LOGON_CHALLENGE     = 0.b
val LOGON_PROOF         = 1.b
val RECONNECT_CHALLENGE = 2.b
val RECONNECT_PROOF     = 3.b

val CLOGON_CHALLENGE_FIXED_LENGTH       = 34
val CLOGON_CHALLENGE_MAX_LENGTH         = CLOGON_CHALLENGE_FIXED_LENGTH + MAX_USERNAME_LEN
val SLOGON_CHALLENGE_MIN_LENGTH         = 3
val SLOGON_CHALLENGE_MAX_LENGTH         = 119 // ignores security bytes
val SLOGON_CHALLENGE_REST_LENGTH        = 116
val CLOGON_PROOF_LENGTH                 = 75
val SLOGON_PROOF_MIN_LENGTH             = 2
val SLOGON_PROOF_MAX_LENGTH             = 26
val SLOGON_PROOF_REST_LENGTH            = 24
val CRECONNECT_CHALLENGE_FIXED_LENGTH   = CLOGON_CHALLENGE_FIXED_LENGTH
val CRECONNECT_CHALLENGE_MAX_LENGTH     = CLOGON_CHALLENGE_MAX_LENGTH
val CRECONNECT_PROOF_LENGTH             = 58

val ACCOUNT_FLAG_GM         = 0x00000001
val ACCOUNT_FLAG_TRIAL      = 0x00000008
val ACCOUNT_FLAG_PROPASS    = 0x00800000